### PR TITLE
Update mxr link to dxr in readme.

### PR DESCRIPTION
**Pull request by SingingTree**
Update link to mozbase code since mxr is now closed.

### CODE REVIEW

**Comment by whimboo** [comment]
As the repository name says this repo is no longer used. All the code has been moved to mozilla-central under testing/mozbase. If we still have mxr listed there, can you please file a bug under testing/mozbase, and get it fixed via a mozreview patch? Thanks.

**Comment by SingingTree** [comment]
I understand. It's the link in the README of the deprecated repo here that links to MXR. Since this repo is still pretty easy to end up at (I got here via search for 'mozsystemmonitor' and the top results contain a lot of forks of this repo), the mxr redirect adds an extra bit of overhead, and as the mxr redirect may go dark at some stage, I think it's worthwhile updating it.

**Comment by whimboo** [comment]
@ahal what do you think?

**Comment by ahal** [comment]
I don't see any harm in merging this pull request, and seems like it could prevent some confusion.

**Comment by whimboo** [comment]
Then lets do it.

**Pull request merged**
